from abc import ABC,abstractmethod

class DatasetAdapter(ABC):
    """Only semantic identifiers cross this interface; mappings are provider-owned."""
    @abstractmethod
    def metric(self, metric_id, period, filters): ...
    @abstractmethod
    def segments(self, metric_id, dimension_id, period, filters): ...
    @abstractmethod
    def quality(self, analysis_scope): ...
    @abstractmethod
    def metric_available(self, metric_id): ...
    @abstractmethod
    def dimension_available(self, dimension_id): ...
    @abstractmethod
    def required_fields(self, metric_id): ...
    @abstractmethod
    def scan_size(self): ...
    @abstractmethod
    def schema(self): ...
